apiVersion: apps/v1
kind: Deployment
metadata:
  name: multithread-interno-deployment
  namespace: producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multithread-interno-react
  template:
    metadata:
      labels:
        app: multithread-interno-react
      annotations:
        kubectl.io/restartedAt: 2026-07-28T23:01:58.0075748-03:00
    spec:
      containers:
        - name: multithread-interno-container
          image: keyssong/react-multithread-interno:latest
          imagePullPolicy: Always              
          ports:
            - containerPort: 5174                
